spring:
  application:
    name: gateway-service

  config:
    import: configserver:http://localhost:9005

  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user/**
          filters:
            - name: CircuitBreaker
              args:
                name: userFallback
                fallbackUri: forward:/fallback/user

        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/order/**
          filters:
            - name: CircuitBreaker
              args:
                name: orderFallback
                fallbackUri: forward:/fallback/order

        - id: payment-service
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/payment/**
          filters:
            - name: CircuitBreaker
              args:
                name: paymentFallback
                fallbackUri: forward:/fallback/payment

server:
  port: 9000

#eureka:
#  instance:
#    hostname: localhost
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka/


management:
  endpoint:
    gateway:
      enabled: true


  endpoints:
    web:
      exposure:
        include:
          - "*"